name: platform_info
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - shell: python
        run: |
          import sys
          print("Python {}.{}.{}".format(*sys.version_info))
      - name: Gyp test
        shell: python
        run: |
          from gyp_xcode_emulation import XcodeVersion
          print(XcodeVersion())
      - name: Display platform information
        shell: python
        run: |
          import inspect
          import platform
          # import sys
          # print(sys.platform, sys.version)
          for name, value in inspect.getmembers(platform):
              if name[0] != "_" and callable(value):
                  try:
                      value = value()
                  except (IndexError, TypeError):
                      continue
                  if str(value).strip("(),' "):
                      print("{:>21}() = {}".format(name, value))
